---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: destroy the instance
      gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: stream-node
        state: absent
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
