---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: remove the firewall rule
      google.cloud.gcp_compute_firewall:
        project: "{{ gcp_project }}"
        name: stream-node
        state: absent
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"

    - name: terminate the instance
      google.cloud.gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        name: stream-node-1
        state: absent
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"

    - name: remove the dns record on cloudflare
      community.general.cloudflare_dns:
        zone: "{{ cf_zone }}"
        record: stream-hub
        state: absent
        api_token: "{{ cf_token }}"
